### ISSUE TITLE
Cannot create new link instance anymore

### ISSUE THREAD

**Issue by FREImedia** [divio/djangocms-link#115]
Hey,

after upgrading to Django 1.10.5 (from 1.9) I'm not able to create a Link widtget within the editor anymore.
I already tried to make and apply migrations which did not solve the problem.

Here is the error message I find in the logs:
```
[Sat Jan 21 13:12:53.217899 2017] [wsgi:error] [pid 26297] Internal Server Error: /admin/cms/page/add-plugin/
[Sat Jan 21 13:12:53.217928 2017] [wsgi:error] [pid 26297] Traceback (most recent call last):
[Sat Jan 21 13:12:53.217934 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
[Sat Jan 21 13:12:53.217940 2017] [wsgi:error] [pid 26297]     response = get_response(request)
[Sat Jan 21 13:12:53.217946 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_$
[Sat Jan 21 13:12:53.217951 2017] [wsgi:error] [pid 26297]     response = self._get_response(request)
[Sat Jan 21 13:12:53.217961 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Sat Jan 21 13:12:53.217967 2017] [wsgi:error] [pid 26297]     response = self.process_exception_by_middleware(e, request)
[Sat Jan 21 13:12:53.217973 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Sat Jan 21 13:12:53.217978 2017] [wsgi:error] [pid 26297]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sat Jan 21 13:12:53.217984 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
[Sat Jan 21 13:12:53.217989 2017] [wsgi:error] [pid 26297]     response = view_func(request, *args, **kwargs)
[Sat Jan 21 13:12:53.217994 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_$
[Sat Jan 21 13:12:53.217999 2017] [wsgi:error] [pid 26297]     response = view_func(request, *args, **kwargs)
[Sat Jan 21 13:12:53.218004 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 211, in inner
[Sat Jan 21 13:12:53.218009 2017] [wsgi:error] [pid 26297]     return view(request, *args, **kwargs)
[Sat Jan 21 13:12:53.218013 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/views/decorators/clickjacking.py", line 39, in wr$
[Sat Jan 21 13:12:53.616782 2017] [wsgi:error] [pid 26297]     resp = view_func(*args, **kwargs)
[Sat Jan 21 13:12:53.616809 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/cms/admin/placeholderadmin.py", line 289, in add_plugin
[Sat Jan 21 13:12:53.616815 2017] [wsgi:error] [pid 26297]     response = plugin_instance.add_view(request)
[Sat Jan 21 13:12:53.616820 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1509, in add_view
[Sat Jan 21 13:12:53.616835 2017] [wsgi:error] [pid 26297]     return self.changeform_view(request, None, form_url, extra_context)
[Sat Jan 21 13:12:53.616841 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
[Sat Jan 21 13:12:53.616848 2017] [wsgi:error] [pid 26297]     return bound_func(*args, **kwargs)
[Sat Jan 21 13:12:53.616853 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
[Sat Jan 21 13:12:53.616859 2017] [wsgi:error] [pid 26297]     response = view_func(request, *args, **kwargs)
[Sat Jan 21 13:12:53.616864 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
[Sat Jan 21 13:12:53.616869 2017] [wsgi:error] [pid 26297]     return func.__get__(self, type(self))(*args2, **kwargs2)
[Sat Jan 21 13:12:53.616874 2017] [wsgi:error] [pid 26297]   File "/usr/lib/python3.4/contextlib.py", line 30, in inner
[Sat Jan 21 13:12:53.616878 2017] [wsgi:error] [pid 26297]     return func(*args, **kwds)
[Sat Jan 21 13:12:53.616884 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1441, in changefo$
[Sat Jan 21 13:12:53.616889 2017] [wsgi:error] [pid 26297]     if form.is_valid():
[Sat Jan 21 13:12:53.616894 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/forms/forms.py", line 169, in is_valid
[Sat Jan 21 13:12:53.616899 2017] [wsgi:error] [pid 26297]     return self.is_bound and not self.errors
[Sat Jan 21 13:12:53.616904 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/forms/forms.py", line 161, in errors
[Sat Jan 21 13:12:53.616909 2017] [wsgi:error] [pid 26297]     self.full_clean()
[Sat Jan 21 13:12:53.616914 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/forms/forms.py", line 372, in full_clean
[Sat Jan 21 13:12:53.616919 2017] [wsgi:error] [pid 26297]     self._post_clean()
[Sat Jan 21 13:12:53.616923 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/forms/models.py", line 398, in _post_clean
[Sat Jan 21 13:12:53.616928 2017] [wsgi:error] [pid 26297]     self.instance.full_clean(exclude=exclude, validate_unique=False)
[Sat Jan 21 13:12:53.616933 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/db/models/base.py", line 1217, in full_clean
[Sat Jan 21 13:12:53.616938 2017] [wsgi:error] [pid 26297]     self.clean()
[Sat Jan 21 13:12:53.616943 2017] [wsgi:error] [pid 26297]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/djangocms_link/models.py", line 163, in clean
[Sat Jan 21 13:12:53.616948 2017] [wsgi:error] [pid 26297]     self._meta.get_field_by_name(anchor_field_name)[0].verbose_name)
[Sat Jan 21 13:12:53.616962 2017] [wsgi:error] [pid 26297] AttributeError: 'Options' object has no attribute 'get_field_by_name'
```

Edit:
I have installed django-cms link via pip:
Django==1.10.5
django-cms==3.4.1
djangocms-link==2.1.0
...

Have you any idea how I can make it work again?

Thank you!
Best,
Matthias

**Comment by FinalAngel** [comment]
@haricot will update here once djangocms-link has been released with the patch

**Comment by FREImedia** [comment]
@haricot Can you already tell me when the patch will be released? :-)

**Comment by FinalAngel** [comment]
@FREImedia sadly not, I'll add it to my tasklist for next week and let you know

**Comment by FinalAngel** [comment]
released :)

**Comment by FREImedia** [comment]
I just upgraded to version 2.1.1 but its still not fixed :-(
```[Fri Mar 03 12:50:29.852648 2017] [wsgi:error] [pid 24561]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/forms/forms.py", line 372, in full_clean
[Fri Mar 03 12:50:29.852653 2017] [wsgi:error] [pid 24561]     self._post_clean()
[Fri Mar 03 12:50:29.852658 2017] [wsgi:error] [pid 24561]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/forms/models.py", line 398, in _post_clean
[Fri Mar 03 12:50:29.852663 2017] [wsgi:error] [pid 24561]     self.instance.full_clean(exclude=exclude, validate_unique=False)
[Fri Mar 03 12:50:29.852668 2017] [wsgi:error] [pid 24561]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/django/db/models/base.py", line 1217, in full_clean
[Fri Mar 03 12:50:29.852673 2017] [wsgi:error] [pid 24561]     self.clean()
[Fri Mar 03 12:50:29.852677 2017] [wsgi:error] [pid 24561]   File "/var/www/virtualenv/www_django/lib/python3.4/site-packages/djangocms_link/models.py", line 163, in clean
[Fri Mar 03 12:50:29.852682 2017] [wsgi:error] [pid 24561]     self._meta.get_field(anchor_field_name).verbose_name)
[Fri Mar 03 12:50:29.852689 2017] [wsgi:error] [pid 24561] AttributeError: 'Options' object has no attribute 'get_field_by_name'
[Fri Mar 03 12:50:29.852698 2017] [wsgi:error] [pid 24561] 
```
